name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Inicializar Terraform
        run: terraform init

      - name: Planejar Terraform
        run: terraform plan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
