name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: sa-east-1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Inicializar Terraform
        run: cd terraform && terraform init

      - name: Destruir Infra Anterior
        run: cd terraform && terraform destroy -auto-approve

      - name: Planejar Terraform
        run: cd terraform && terraform plan

      - name: Aplicar Terraform
        run: cd terraform && terraform apply -auto-approve

      - name: Pegar IP Publico
        run: cd terraform && terraform output -raw public_ip
